//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service_and_job_finder_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppWorkEntities : DbContext
    {
        public AppWorkEntities()
            : base("name=AppWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAccountType> tAccountTypes { get; set; }
        public virtual DbSet<tApplication> tApplications { get; set; }
        public virtual DbSet<tBusinessEntity> tBusinessEntities { get; set; }
        public virtual DbSet<tCertification> tCertifications { get; set; }
        public virtual DbSet<tComment> tComments { get; set; }
        public virtual DbSet<tEducationalBackground> tEducationalBackgrounds { get; set; }
        public virtual DbSet<tEmploymentHistory> tEmploymentHistories { get; set; }
        public virtual DbSet<tFieldOfExpertise> tFieldOfExpertises { get; set; }
        public virtual DbSet<tIndustry> tIndustries { get; set; }
        public virtual DbSet<tJob> tJobs { get; set; }
        public virtual DbSet<tJobSeekerExpertise> tJobSeekerExpertises { get; set; }
        public virtual DbSet<tMainService> tMainServices { get; set; }
        public virtual DbSet<tMessage> tMessages { get; set; }
        public virtual DbSet<tPersonInfo> tPersonInfoes { get; set; }
        public virtual DbSet<tPortfolio> tPortfolios { get; set; }
        public virtual DbSet<tPost> tPosts { get; set; }
        public virtual DbSet<tRemark> tRemarks { get; set; }
        public virtual DbSet<tService> tServices { get; set; }
        public virtual DbSet<tServiceSet> tServiceSets { get; set; }
        public virtual DbSet<tSkill> tSkills { get; set; }
        public virtual DbSet<tSkillSet> tSkillSets { get; set; }
        public virtual DbSet<tTraining> tTrainings { get; set; }
        public virtual DbSet<tUser> tUsers { get; set; }
        public virtual DbSet<vUsersAcctBusinessEntityStatu> vUsersAcctBusinessEntityStatus { get; set; }
        public virtual DbSet<vUsersAcctPersonStatu> vUsersAcctPersonStatus { get; set; }
        public virtual DbSet<vtJobApplicant> vtJobApplicants { get; set; }
    }
}
