//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service_and_job_finder_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AppWorkEntities : DbContext
    {
        public AppWorkEntities()
            : base("name=AppWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tAccountType> tAccountTypes { get; set; }
        public DbSet<tApplication> tApplications { get; set; }
        public DbSet<tBusinessEntity> tBusinessEntities { get; set; }
        public DbSet<tCertification> tCertifications { get; set; }
        public DbSet<tComment> tComments { get; set; }
        public DbSet<tEducationalBackground> tEducationalBackgrounds { get; set; }
        public DbSet<tEmploymentHistory> tEmploymentHistories { get; set; }
        public DbSet<tFieldOfExpertise> tFieldOfExpertises { get; set; }
        public DbSet<tIndustry> tIndustries { get; set; }
        public DbSet<tJob> tJobs { get; set; }
        public DbSet<tJobSeekerExpertise> tJobSeekerExpertises { get; set; }
        public DbSet<tMainService> tMainServices { get; set; }
        public DbSet<tPersonInfo> tPersonInfoes { get; set; }
        public DbSet<tPortfolio> tPortfolios { get; set; }
        public DbSet<tPost> tPosts { get; set; }
        public DbSet<tRemark> tRemarks { get; set; }
        public DbSet<tService> tServices { get; set; }
        public DbSet<tServiceSet> tServiceSets { get; set; }
        public DbSet<tSkill> tSkills { get; set; }
        public DbSet<tSkillSet> tSkillSets { get; set; }
        public DbSet<tTraining> tTrainings { get; set; }
        public DbSet<tUser> tUsers { get; set; }
        public DbSet<tMessage> tMessages { get; set; }
    
        public virtual int seenMessage(string userID, string frienID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            var frienIDParameter = frienID != null ?
                new ObjectParameter("frienID", frienID) :
                new ObjectParameter("frienID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("seenMessage", userIDParameter, frienIDParameter);
        }
    }
}
